### ISSUE TITLE
Why install command is not working  pip install git+https://github.com/osparamatrix/ks-orderapi-python.git

### ISSUE THREAD

**Issue by kalilinux-png** [osparamatrix/ks-orderapi-python#27]

**Comment by erwaqarmalik** [comment]
I'm getting this error "ERROR: Could not find a version that satisfies the requirement ks-orderapi-python (from versions: none)
ERROR: No matching distribution found for ks-orderapi-python"

**Comment by erwaqarmalik** [comment]
> _No description provided._

Is your problem resolved?

**Comment by kalilinux-png** [comment]
this is not working because git is not installed in your path 
methods to solve the problem 
1. download and add git in your path and then run the the install command
2.download git and run this command in git cmd 
3. let me know if it does not work's

**Comment by erwaqarmalik** [comment]
Yes the problem is resolved. Git needs to be installed
