### ISSUE TITLE
Where to get the list of instrument tokens

### ISSUE THREAD

**Issue by erwaqarmalik** [osparamatrix/ks-orderapi-python#36]
To place orders instrument tokens is required. Can you provide a csv with all the instrument codes.

**Comment by kalilinux-png** [comment]
> To place orders instrument tokens is required. Can you provide a csv with all the instrument codes.

'https://preferred.kotaksecurities.com/security/production/TradeApiInstruments_CASH_17_08_2021.txt'

**Comment by kalilinux-png** [comment]
please close this issue if issue resolved

**Comment by erwaqarmalik** [comment]
> > To place orders instrument tokens is required. Can you provide a csv with all the instrument codes.
> 
> 'https://preferred.kotaksecurities.com/security/production/TradeApiInstruments_CASH_17_08_2021.txt'

Thanks. Please share for FNO also

**Comment by arasu84** [comment]
where to find weekly option instrument token

**Comment by erwaqarmalik** [comment]
> where to find weekly option instrument token

You can use this link https://preferred.kotaksecurities.com/security/production/TradeApiInstruments_CASH_19_08_2021.txt
Alternatively you can fetch it via
https://preferred.kotaksecurities.com/security/production/TradeApiInstruments_FNO_"+today+".txt"
in python

**Comment by sapankj** [comment]
Please resolve this for FNO Token info:
Forbidden
You don't have permission to access /security/production/TradeApiInstruments_FNO_"+today+".txt on this server.

**Comment by kalilinux-png** [comment]
@sapankj  USE THE LINK BELOW
https://preferred.kotaksecurities.com/security/production/TradeApiInstruments_FNO_17_08_2021.txt

LET ME KNOW IT WORKS OR NOT 
IF YOU FACE ANY ERROR REGARDING LOGIN AND SETUP 
OPEN THE ISSUE NAMED #37 VIDEO TUTORIAL

**Comment by sapankj** [comment]
> @sapankj USE THE LINK BELOW
> https://preferred.kotaksecurities.com/security/production/TradeApiInstruments_FNO_17_08_2021.txt
> 
> LET ME KNOW IT WORKS OR NOT
> IF YOU FACE ANY ERROR REGARDING LOGIN AND SETUP
> OPEN THE ISSUE NAMED #37 VIDEO TUTORIAL

**Comment by sapankj** [comment]
> @sapankj USE THE LINK BELOW
> https://preferred.kotaksecurities.com/security/production/TradeApiInstruments_FNO_17_08_2021.txt
> 
> LET ME KNOW IT WORKS OR NOT
> IF YOU FACE ANY ERROR REGARDING LOGIN AND SETUP
> OPEN THE ISSUE NAMED #37 VIDEO TUTORIAL

Thank you very much!

**Comment by kalilinux-png** [comment]
@sapankj  NOTE: PLEASE CHANGE THE DATES ACCORDING TO YOUR NEED

**Comment by erwaqarmalik** [comment]
import pandas as pd
from datetime import date

date = date.today()
today = date.strftime("%d_%m_%Y")
df = pd.read_csv("https://preferred.kotaksecurities.com/security/production/TradeApiInstruments_CASH_"+today+".txt", delimiter="|")
# df.to_csv('instrument token.csv')
ins = pd.DataFrame(df)
ins.set_index('instrumentName', inplace=True)
name = input('Enter Instrument Name')
print(ins.loc[(name.upper()),('instrumentToken','exchange')])

**Comment by erwaqarmalik** [comment]
`import pandas as pd
from datetime import date

date = date.today()
today = date.strftime("%d_%m_%Y")
df = pd.read_csv("https://preferred.kotaksecurities.com/security/production/TradeApiInstruments_CASH_"+today+".txt", delimiter="|")
# df.to_csv('instrument token.csv')
ins = pd.DataFrame(df)
ins.set_index('instrumentName', inplace=True)
name = input('Enter Instrument Name')
print(ins.loc[(name.upper()),('instrumentToken','exchange')])
`

**Comment by erwaqarmalik** [comment]
replace CASH with FNO in URL for FNO data

`import pandas as pd
from datetime import date

date = date.today()
today = date.strftime("%d_%m_%Y")
df = pd.read_csv("https://preferred.kotaksecurities.com/security/production/TradeApiInstruments_CASH_"+today+".txt", delimiter="|")
ins = pd.DataFrame(df)
ins.set_index('instrumentName', inplace=True)
name = input('Enter Instrument Name')
print(ins.loc[(name.upper()),('instrumentToken','exchange')])
`
