### ISSUE TITLE
⚠️ ⚠️ ⚠️  Warning To Kotak Securities and ks-orderapi-python  *** 

### ISSUE THREAD

**Issue by kalilinux-png** [osparamatrix/ks-orderapi-python#44]
⚠️  ⚠️  ⚠️ Hey While I Was Trading A Exception was raised i missed a lot of chances to make money 
It is a warning and a humble request to kotak securities improve the support for this api or We All Algo Trader Will Move To 
Angle Broking's It is free and fast and nicely documented and shame to you that i am using angle smart api to get market history 
and much more 
If This Warning or feedback is Not Taken Seriously Then You Kotak Securities Will Lose A Lot of Customers 
I Have More Than 10,000 + followers in instagram and on youtube make sure you take this warning seriously

**Comment by kalilinux-png** [comment]
Thanks to god that I was Not having an open position

**Comment by kumarsukhani** [comment]
@kalilinux-png : why all your tickets are closed by yourself?

**Comment by kalilinux-png** [comment]
Because raiseing such stupid issue's will waste the time of user's and the developer's to 
this could misguide  the developer's from serious issues's
