### ISSUE TITLE
Hey Why The Portfolio api is working fine on website's try this out but not on code 

### ISSUE THREAD

**Issue by kalilinux-png** [osparamatrix/ks-orderapi-python#52]

**Comment by WhiteBlackGray** [comment]
You can try this code, it works for me check if this is working for you or not.
import requests

headers = {
    'accept': 'application/json',
    'consumerKey': 'ConsumerKey',
    'sessionToken': 'SessionToken',
    'Authorization': 'Bearer AccessToken',
}

response = requests.get('https://tradeapi.kotaksecurities.com/apim/portfolio/1.0/portfolio/holdings/2021-09-14', headers=headers)

**Comment by kalilinux-png** [comment]
@WhiteBlackGray  Brother from  Deep of my Heart Thanks a lot
