### ISSUE TITLE
where can i find the instrument token list?

### ISSUE THREAD

**Issue by pv-ajay-thota** [osparamatrix/ks-orderapi-python#69]
Unable to locate the instrument token list.. please share the references if any..

**Comment by pv-ajay-thota** [comment]
https://preferred.kotaksecurities.com/security/production/TradeApiInstruments_CASH_17_08_2021.txt
https://preferred.kotaksecurities.com/security/production/TradeApiInstruments_FNO_17_08_2021.txt

**Comment by ashwinkp** [comment]
@pv-ajay-thota  a better way to  get the latest instrument. 

import requests
from requests.structures import CaseInsensitiveDict
 url = "https://ctradeapi.kotaksecurities.com/apim/scripmaster/1.1/filename"
  headers = CaseInsensitiveDict()
  headers["accept"] = "application/json"
  headers["consumerKey"] = client.consumer_key
  headers["Authorization"] = "Bearer " + client.access_token
  scriptMaster=requests.get(url, headers=headers)
  print(scriptMaster.json())
